//Copyright (c) Piet Wauters 2022 <piet.wauters@gmail.com>
#define LONG_COUNT_B_INIT_SABRE 2000
#define LONG_COUNT_C_INIT_SABRE 2000
// below are more less arbitrary. After about 30 seconds I will stop buzzing; After about a minute I will switch to epee
#define LONG_COUNT_NOTCONNECTED_INIT 255 * 200
#define LONG_COUNT_NOTCONNECTED_STOP_BUZZING 255 * 100

/* Insert the constants generated by the exceltool here  */
/************************************************************************************************/
/* Do not alter this file directly. Make changes in the Xcel file TimingConstants.xls */
/************************************************************************************************/
/************************************************************************************************/
/* Timing Constants for Foil  */
/************************************************************************************************/
#define FOIL_LOCK_TIME  300	// Time in milliseconds
#define COUNT_B1_INIT_FOIL  12	/*  T = 14ms/1.1   */
#define COUNT_C1_INIT_FOIL  5	/*  T = (n-1)*NrPhases*Time/Phase   */
#define COUNTER_MINIMAL_BREAK  1
#define LONG_COUNT_B_INIT_FOIL 1900
#define LONG_COUNT_C_INIT_FOIL 1900
#define COUNT_ON_PARRY_INIT_FOIL  5
#define COUNT_OFF_PARRY_INIT_FOIL  43

/************************************************************************************************/
/* Timing Constants for Epee  */
/************************************************************************************************/
#define EPEE_LOCK_TIME 45	// Time in milliseconds
#define COUNT_C1_INIT_EPEE  5	/*  T = 0.097 * n   */
#define LONG_COUNT_C_INIT_EPEE  1600
/************************************************************************************************/
/* Timing Constants for Sabre  */
/************************************************************************************************/
#define SABRE_LOCK_TIME  170	// Time in milliseconds
#define COUNT_B1_INIT_SABRE  6	/*  T = (n-1)*NrPhases*Time/Phase   */
#define COUNT_C1_INIT_SABRE  2	/*  T = (n-1)*NrPhases*Time/Phase   */
#define BLOCKINGPERIOD1  4	/*  T = (n-1)*NrPhases*Time/Phase   */
#define BLOCKINGPERIOD2  21	/*  T = (n-1)*NrPhases*Time/Phase   */
//#define TWO_SECONDS  87	/* T = n*LockTimePeriod  */

/************************************************************************************************/
/* Timing Constants for ESP32 implementation                                                    */
/************************************************************************************************/
// Below values are in microseconds
#define FULLSCANDURATION_EPEE 1000
#define FULLSCANDURATION_FOIL 1100
#define FULLSCANDURATION_SABRE 480
